spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/frontleaves-master-control
    username: "frontleaves-master-control"
    password: "123456"
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password:
logging:
  level:
    com.xlf: debug
    com.frontleaves: debug
    com.frontleaves.mapper: info
xutil:
  mail:
    nickname: ""